name: Deploy web to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Instala PNPM de forma global para que esté en PATH
      - name: Install pnpm
        shell: pwsh
        run: |
          npm i -g pnpm@9.15.9
          pnpm -v

      - name: Install deps
        shell: pwsh
        run: pnpm install --frozen-lockfile

      - name: Build web
        shell: pwsh
        working-directory: apps/web
        run: pnpm build

      - name: Prepare static files
        shell: pwsh
        working-directory: apps/web
        run: |
          if (-not (Test-Path out)) { throw "Missing 'out' directory. Check next.config.js (output: export)." }
          New-Item -ItemType File -Path out/.nojekyll -Force | Out-Null
          Copy-Item out/index.html out/404.html -Force

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    needs: build
    runs-on: windows-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
