name: Deploy web to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      # ✅ Put pnpm on PATH via Corepack (respects your packageManager version)
      - name: Enable Corepack (pnpm)
        run: |
          corepack enable
          # Pin to your repo's version if you want; else Corepack uses packageManager field
          corepack prepare pnpm@9.15.9 --activate
          pnpm -v

      # Monorepo install at the root
      - name: Install deps (monorepo root)
        run: pnpm install --frozen-lockfile

      # Build only the web app; it will output to apps/web/out (Next "output: export")
      - name: Build static site
        env:
          GITHUB_ACTIONS: "true"
        run: pnpm --filter @edu-os/web build

      - name: Add .nojekyll and 404
        run: |
          touch apps/web/out/.nojekyll
          cp apps/web/out/index.html apps/web/out/404.html || true

      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web/out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
